### ISSUE TITLE
please fix og image on your GH page

### ISSUE THREAD

**Issue by adamnicolson** [icons8/welovesvg#1]
Id like to pin your page on my pintrest icons board but your paths to the OG image are broksed. Please can you fix or add a priddy image to your page somewhere. Much love

**Comment by visualpharm** [comment]
Thanks for reporting! We'll fix it with the next deploy.

**Comment by adamnicolson** [comment]
not sure if you got it right.

<meta property="og:image" content="" ng-attr-content="{{icon.previewPng}}"
ng-if="icon.previewPng">https://icons8.com/welovesvg

On Tue, Oct 13, 2015 at 6:47 PM, Alexey Zakharenko <notifications@github.com

**Comment by YoginAlex** [comment]
@adamnicolson you're right.
Now the changes at our demo server.
On production will be very soon.
Also fix on GitHub pages http://icons8.github.io/welovesvg/
