### ISSUE TITLE
How can I convert svg to png

### ISSUE THREAD

**Issue by lovebdsobuj** [icons8/welovesvg#2]
How can I convert svg to png...?

I try with this tool [svg2ttf](https://github.com/fontello/svg2ttf).

But maybe, that tool aren't suitable, Because I got error message.

> Error: Can't find <font> tag. Make sure you SVG file is font, not image.

**Comment by visualpharm** [comment]
You may use https://icons8.com/web-app :
![23 500 icons - free download icons8 2016-03-29 20-01-39](https://cloud.githubusercontent.com/assets/5383670/14133254/4ab4b6f6-f5e9-11e5-85cd-92f10cc1141e.png)

**Comment by lovebdsobuj** [comment]
Nice application, but I want to work offline...
also there size limitation.

**Comment by visualpharm** [comment]
Size limit is only for Icons8's icons; if you upload your own icons, all the sizes of the world are yours.

For offline use, any graphic editor is fine: Illustrator, Inkscape, Sketch. Finally, you can even make screenshots from any viewer (such as a browser).

**Comment by lovebdsobuj** [comment]
> Size limit is only for Icons8's icons; if you upload your own icons, all the sizes of the world are yours.

Oh, really, Then I should try `Icons8 WebApp`...

Thank you @visualpharm...
